- name: Run Server
  ansible.builtin.systemd_service:
    name: '{{ minecraft_settings.modpack }}'
    state: started
    enabled: true
  become: true
  become_method: su
  become_exe: sudo su -
- name: Verify Server
  ansible.builtin.shell: 
    cmd: tail /usr/local/bin/{{ minecraft_settings.modpack }}/logs/latest.log -n 500
  register: server_status
  until: server_status.stdout.find('Done') != -1
  retries: 12
  delay: 20