- name: Check if Server Exists
  ansible.builtin.stat:
    path: ~/.config/systemd/user/{{ minecraft_settings.modpack }}.service
  register: server_exists
- name: Stop Server
  ansible.builtin.systemd_service:
    name: '{{ minecraft_settings.modpack }}'
    state: stopped
    enabled: false
    scope: user
  when: server_exists.stat.exists == true
