- name: Check if Server Exists
  ansible.builtin.stat:
    path: ~/.config/systemd/user/{{ modpack }}.service
  register: server_exists
- name: Stop Server
  ansible.builtin.systemd_service:
    name: '{{ modpack }}'
    state: stopped
    scope: user
  when: server_exists.stat.exists == true
