- name: Check if Server Exists
  ansible.builtin.stat:
    path: /etc/systemd/system/{{ minecraft_settings.modpack }}.service
  register: server_exists
- name: Stop Server
  ansible.builtin.systemd_service:
    name: '{{ minecraft_settings.modpack }}'
    state: stopped
    enabled: false
  become: true
  become_method: su
  become_exe: sudo su -
  when: server_exists.stat.exists == true
